# Generated by Django 4.1.1 on 2022-10-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, unique=True)),
                ('url', models.CharField(max_length=240)),
                ('image_url', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holding_id', models.IntegerField(unique=True)),
                ('zone', models.CharField(max_length=3)),
                ('brand', models.CharField(max_length=240)),
                ('dob', models.DateField()),
                ('species', models.CharField(max_length=240)),
                ('breed', models.CharField(max_length=240)),
                ('sex', models.CharField(max_length=240)),
                ('age', models.IntegerField()),
                ('colour', models.CharField(max_length=240)),
            ],
        ),
    ]
