# Generated by Django 4.1.1 on 2022-10-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='img',
            field=models.FileField(default='BOOK IMAGE', upload_to='books/'),
        ),
    ]
