# Generated by Django 4.1.1 on 2022-10-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='img',
            field=models.FileField(default='BOOK IMAGE', upload_to='static/books/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.FileField(default='POST IMAGE', upload_to='static/posts/'),
        ),
    ]
