# Generated by Django 4.1.1 on 2022-10-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_books_img_alter_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='img',
            field=models.FileField(default='BOOK IMAGE', upload_to='books/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.FileField(default='POST IMAGE', upload_to='posts/'),
        ),
    ]
