# Generated by Django 4.1.1 on 2022-10-11 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_books_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created',)},
        ),
    ]
